# Generated by Django 5.1.3 on 2025-03-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="pic",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="pics/pictures",
                verbose_name="تصویر پروفایل",
            ),
        ),
    ]
