# Generated by Django 5.1.3 on 2025-04-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_alter_contact_pic_alter_contact_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="published",
                max_length=10,
                verbose_name="وضعیت",
            ),
        ),
    ]
