# Generated by Django 5.1.3 on 2025-04-06 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0004_alter_contact_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="نویسنده",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="pic",
            field=models.FileField(
                blank=True,
                default="media/pics/pictures/low-qlt-thumb.jpg",
                null=True,
                upload_to="pics/pictures",
                verbose_name="عکس مخاطب",
            ),
        ),
    ]
