# Generated by Django 5.1.3 on 2025-04-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0005_alter_contact_author_alter_contact_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="pic",
            field=models.FileField(
                blank=True,
                default="pics/pictures/low-qlt-thumb.jpg",
                null=True,
                upload_to="pics/pictures",
                verbose_name="عکس مخاطب",
            ),
        ),
    ]
