# Generated by Django 5.1.3 on 2025-04-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usernamesignup",
                    models.CharField(max_length=255, verbose_name="نام کاربری"),
                ),
                (
                    "emailsignup",
                    models.EmailField(max_length=254, verbose_name="ایمیل"),
                ),
                (
                    "phonesignup",
                    models.CharField(max_length=11, verbose_name="شماره تلفن"),
                ),
                (
                    "passwordsignup",
                    models.CharField(max_length=255, verbose_name="پسورد"),
                ),
            ],
            options={
                "verbose_name": "SIGN UP",
                "verbose_name_plural": "SING UP",
            },
        ),
    ]
