# Generated by Django 5.1.3 on 2025-04-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CallInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namecall", models.CharField(max_length=255, verbose_name="نام")),
                ("emailcall", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("messagecall", models.TextField(verbose_name="پیام")),
                (
                    "createdcall_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ارسال"),
                ),
            ],
            options={
                "verbose_name": "CALLS",
                "verbose_name_plural": "CALLS",
            },
        ),
    ]
